import {useCallback,useEffect,useMemo,useState} from 'react';
import {decodeEventLog,encodeFunctionData,formatEther,parseEther,type Address} from 'viem';
import {useAccount,useConnect,useDisconnect,usePublicClient,useReadContract,useWriteContract} from 'wagmi';
import {bscTestnet} from './config/chain';
import {factoryAbi,factoryAddress,vaultAbi,walletAbi} from './config/contracts';
import {calculateAllocations,validatePreset,type ContainerRule} from './logic/allocation';
import {enableMandatoryNotifications} from './notifications';

type ChainPayment={id:bigint;amount:bigint;state:number;temporaryUnlockAt:bigint;decisionAt:bigint;allocations:bigint[]};
type Preset={id:string;onchainPresetId:string;name:string;archived:boolean;deleted:boolean;activeFunds:string;containers:{name:string;percentage:number;lockDurationSeconds:string;priority:number}[]};
const priorityNames=['Very Low','Low','Medium','High','Very High'];
const empty=():ContainerRule=>({name:'',percentage:0,lockDuration:0,priority:2});
const api=()=>import.meta.env.VITE_API_URL||'http://localhost:8787';

function Countdown({until}:{until:bigint}){const[remaining,setRemaining]=useState(()=>Number(until)*1000-Date.now());useEffect(()=>{const t=setInterval(()=>setRemaining(Number(until)*1000-Date.now()),1000);return()=>clearInterval(t)},[until]);if(remaining<=0)return <span className="ok">Ready</span>;const s=Math.floor(remaining/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;return <span>{h>0?h+'h ':''}{m}m {sec}s</span>}

export default function App(){
const{address,isConnected,chainId}=useAccount();const{connect,connectors}=useConnect();const{disconnect}=useDisconnect();const client=usePublicClient();const{writeContractAsync}=useWriteContract();
const[wallet,setWallet]=useState<Address|null>(()=>localStorage.getItem('allocash.wallet') as Address|null);const[vault,setVault]=useState<Address|null>(()=>localStorage.getItem('allocash.vault') as Address|null);
const[presetName,setPresetName]=useState('Salary');const[containers,setContainers]=useState<ContainerRule[]>([empty(),{...empty(),name:'Free Money',percentage:100,priority:1}]);const[presets,setPresets]=useState<Preset[]>([]);const[suggestion,setSuggestion]=useState<any>(null);const[payments,setPayments]=useState<ChainPayment[]>([]);const[notifications,setNotifications]=useState<any[]>([]);const[deposit,setDeposit]=useState('0.1');const[status,setStatus]=useState('Connect a wallet to begin.');const[tab,setTab]=useState('active');const[push,setPush]=useState(false);
const balance=useReadContract({address:vault??undefined,abi:vaultAbi,functionName:'totalProtectedBalance',query:{enabled:Boolean(vault)}}).data as bigint|undefined;
const validation=validatePreset(containers);const total=useMemo(()=>containers.reduce((s,c)=>s+c.percentage,0),[containers]);

const sync=useCallback(async()=>{if(!address||!vault||!client)return;try{await fetch(api()+'/v1/indexer/sync',{method:'POST'}).catch(()=>undefined);const pr=await fetch(api()+'/v1/presets/'+address).then(r=>r.json());const nt=await fetch(api()+'/v1/notifications/'+address).then(r=>r.json());const sg=await fetch(api()+'/v1/suggestions/'+address).then(r=>r.json());setPresets(pr.presets||[]);setNotifications(nt.notifications||[]);setSuggestion(sg.suggestion||null);const latest=await client.getBlockNumber();const from=latest>2000n?latest-2000n:0n;const logs=await client.getLogs({address:vault,event:vaultAbi.find((x:any)=>x.type==='event'&&x.name==='IncomingPayment') as any,fromBlock:from,toBlock:'latest'} as any);const rows=await Promise.all(logs.map(async(l:any)=>{const p:any=await client.readContract({address:vault,abi:vaultAbi,functionName:'payments',args:[l.args.paymentId]});const ids=await client.readContract({address:vault,abi:vaultAbi,functionName:'paymentAllocations',args:[l.args.paymentId]});return{id:l.args.paymentId,amount:p[0],state:Number(p[5]),temporaryUnlockAt:p[3],decisionAt:p[4],allocations:ids}}));setPayments(rows.reverse())}catch(e){setStatus(e instanceof Error?e.message:'Synchronization failed.')}} ,[address,vault,client]);
useEffect(()=>{sync();const t=setInterval(sync,30000);return()=>clearInterval(t)},[sync]);

async function register(w:Address,v:Address,block?:bigint){if(!address)return;await fetch(api()+'/v1/users/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({walletAddress:address,smartAccount:w,vaultAddress:v,createdBlock:block?.toString()||'0'})}).catch(()=>undefined)}
async function recordTx(hash:string,action:string){if(!address)return;await fetch(api()+'/v1/transactions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({walletAddress:address,txHash:hash,action,status:'CONFIRMED',confirmedAt:new Date().toISOString()})}).catch(()=>undefined)}
async function txVault(data:string,label:string){if(!wallet||!client)throw new Error('Smart account is not available.');setStatus(label+': confirm in your wallet…');const hash=await writeContractAsync({address:wallet,abi:walletAbi,functionName:'executeVault',args:[data as any],chainId:97});await client.waitForTransactionReceipt({hash});await recordTx(hash,label);await sync();setStatus(label+': confirmed on-chain.');return hash}
async function createAccount(){if(!address||chainId!==97)return;try{const hash=await writeContractAsync({address:factoryAddress,abi:factoryAbi,functionName:'createWallet',args:[address],chainId:97});if(!client)return;const receipt=await client.waitForTransactionReceipt({hash});const log=receipt.logs.find((x:any)=>x.address.toLowerCase()===factoryAddress.toLowerCase());if(!log)throw new Error('WalletCreated event missing from confirmed receipt.');const d:any=decodeEventLog({abi:factoryAbi,data:log.data,topics:log.topics});setWallet(d.args.wallet);setVault(d.args.vault);localStorage.setItem('allocash.wallet',d.args.wallet);localStorage.setItem('allocash.vault',d.args.vault);await register(d.args.wallet,d.args.vault,receipt.blockNumber);setStatus('Dedicated smart account and protected pre-vault created.')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Account creation failed.')}}
async function receive(){if(!vault||chainId!==97)return;try{const hash=await writeContractAsync({address:vault,abi:vaultAbi,functionName:'recordIncoming',value:parseEther(deposit),chainId:97});if(client)await client.waitForTransactionReceipt({hash});await recordTx(hash,'Incoming payment');await sync();setStatus('Incoming payment confirmed in protected pre-vault.')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Incoming payment failed.')}}
async function createPreset(){if(validation||!wallet)return;if(!window.confirm('Review complete. Confirm this preset is correct. The next wallet confirmation will make it immutable on-chain.'))return;try{const input=containers.map(c=>({name:c.name,percentage:c.percentage,lockDuration:c.lockDuration,priority:c.priority,exists:true}));await txVault(encodeFunctionData({abi:vaultAbi,functionName:'createPreset',args:[presetName,input]}),'Immutable preset creation')}catch(e:any){setStatus(e instanceof Error?e.message:'Preset creation failed.')}}
async function allocate(p:ChainPayment,id:string){if(!client||!vault)return;try{const rule=presets.find(x=>x.onchainPresetId===id);if(!rule)throw new Error('Preset is not indexed yet.');const chain:any=await client.readContract({address:vault,abi:vaultAbi,functionName:'payments',args:[p.id]});const preview=calculateAllocations(chain[0],rule.containers.map(c=>({name:c.name,percentage:c.percentage,lockDuration:Number(c.lockDurationSeconds),priority:c.priority as any})));const text='Review allocation for '+formatEther(chain[0])+' tBNB:\n\n'+preview.map(x=>x.name+': '+formatEther(x.amount)+' tBNB').join('\n')+'\n\nConfirm in app, then confirm the wallet transaction.';if(!window.confirm(text))return;await txVault(encodeFunctionData({abi:vaultAbi,functionName:'applyPreset',args:[p.id,BigInt(id)]}),'Allocation')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Allocation failed.')}}
async function lock(p:ChainPayment){if(!window.confirm('Temporarily lock this payment for one hour?'))return;try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'temporaryLock',args:[p.id]}),'Temporary lock')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Lock failed.')}}
async function expire(p:ChainPayment){try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'expireTemporaryLock',args:[p.id]}),'End temporary lock')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Could not reopen decision.')}}
async function relock(p:ChainPayment){try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'autoTemporaryRelock',args:[p.id]}),'Permissionless re-lock')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Re-lock is not yet available.')}}
async function unlock(id:bigint){try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'unlockAllocation',args:[id]}),'Unlock')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Unlock failed.')}}
async function withdraw(id:bigint,amount:bigint){if(!address)return;if(!window.confirm('Authorize spending '+formatEther(amount)+' tBNB to your connected wallet?'))return;try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'withdraw',args:[id,address,amount]}),'Withdrawal')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Withdrawal failed.')}}
async function archive(id:string){const reason=window.prompt('Why are you archiving this preset?');if(!reason?.trim())return;try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'archivePreset',args:[BigInt(id),reason]}),'Archive preset')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Archive failed.')}}
async function del(id:string){if(!window.confirm('Delete this preset? On-chain history is never erased.'))return;try{await txVault(encodeFunctionData({abi:vaultAbi,functionName:'deletePreset',args:[BigInt(id)]}),'Delete preset')}catch(e:any){setStatus(e?.shortMessage||e?.message||'Delete failed.')}}
async function enablePush(){if(!address)return;try{await enableMandatoryNotifications(address);setPush(true);setStatus('Web Push enabled.')}catch(e){setStatus(e instanceof Error?e.message:'Push setup failed.')}}
const visible=tab==='active'?presets.filter(p=>!p.archived&&!p.deleted):presets.filter(p=>p.archived&&!p.deleted);
return <main className="shell"><header><div><p className="eyebrow">ALLOCASH</p><h1>Money with intention.</h1><p className="muted">On-chain financial state. Explicit decisions. No custody.</p></div><div className="walletBox">{isConnected?<><span>{address?.slice(0,6)}…{address?.slice(-4)}</span><button onClick={()=>disconnect()}>Disconnect</button></>:<button onClick={()=>connect({connector:connectors[0]})}>Connect wallet</button>}</div></header>
{chainId&&chainId!==97&&<div className="warning">Switch to BSC Testnet (chain 97).</div>}
<section className="grid"><article className="card hero"><span className="label">PROTECTED PRE-VAULT</span><strong>{formatEther(balance??0n)} tBNB</strong><p className="muted">Balance is read directly from the vault contract.</p>{!wallet?<button className="primary" disabled={!isConnected||chainId!==97} onClick={createAccount}>Create dedicated smart account</button>:<code>{wallet}</code>}</article><article className="card"><span className="label">RECEIVE</span><input value={deposit} onChange={e=>setDeposit(e.target.value)} inputMode="decimal"/><button className="primary" disabled={!vault||chainId!==97} onClick={receive}>Receive into pre-vault</button><button onClick={enablePush} disabled={!address}>{push?'Web Push enabled':'Enable safety notifications'}</button></article></section>
<nav className="tabs"><button onClick={()=>setTab('active')}>Active presets</button><button onClick={()=>setTab('archived')}>Archived presets</button><button onClick={()=>setTab('history')}>Payment history</button></nav>
{tab!=='history'&&<section className="card"><span className="label">PRESETS</span><h2>{tab==='active'?'Immutable active presets':'Archived presets'}</h2>{tab==='active'&&suggestion&&<div className="notice"><b>Suggested from previous usage: {suggestion.name}</b><small>This is only a suggestion. Choosing it still requires your explicit confirmation and wallet authorization.</small><button onClick={()=>{const p=presets.find(x=>x.onchainPresetId===String(suggestion.presetId));if(p){setPresetName(p.name);setContainers(p.containers.map(c=>({name:c.name,percentage:c.percentage,lockDuration:Number(c.lockDurationSeconds),priority:c.priority as any})))}}}>Review suggestion</button></div>}{visible.map(p=><div className="payment" key={p.id}><div><b>#{p.onchainPresetId} · {p.name}</b><span>{p.containers.map(c=>c.name+' '+c.percentage+'%').join(' · ')}</span><small>{p.activeFunds==='0'?'No active funds':formatEther(BigInt(p.activeFunds))+' tBNB active'}</small></div>{tab==='active'&&<div className="actions"><button disabled={p.activeFunds!=='0'} onClick={()=>archive(p.onchainPresetId)}>Archive</button><button disabled={p.activeFunds!=='0'} onClick={()=>del(p.onchainPresetId)}>Delete</button></div>}</div>)}{tab==='active'&&<><div className="sectionHead"><span className={total===100?'ok':'bad'}>{total}% / 100%</span></div><input value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Preset name"/>{containers.map((c,i)=><div className="row" key={i}><input placeholder="Container" value={c.name} onChange={e=>setContainers(xs=>xs.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="0" max="100" value={c.percentage} onChange={e=>setContainers(xs=>xs.map((x,j)=>j===i?{...x,percentage:Number(e.target.value)}:x))}/><input type="number" min="0" value={c.lockDuration/86400} onChange={e=>setContainers(xs=>xs.map((x,j)=>j===i?{...x,lockDuration:Number(e.target.value)*86400}:x))}/><select value={c.priority} onChange={e=>setContainers(xs=>xs.map((x,j)=>j===i?{...x,priority:Number(e.target.value) as any}:x))}>{priorityNames.map((x,j)=><option key={x} value={j}>{x}</option>)}</select></div>)}<div className="actions"><button disabled={containers.length>=10} onClick={()=>setContainers(x=>[...x,empty()])}>Add container</button><button className="primary" disabled={!wallet||Boolean(validation)} onClick={createPreset}>Review & confirm immutable preset</button></div>{validation&&<p className="bad">{validation}</p>}</>}</section>}
{tab==='history'&&<section className="card"><span className="label">PAYMENT HISTORY</span><h2>Every payment</h2>{payments.map(p=><div className="payment" key={p.id.toString()}><div><b>Payment #{p.id.toString()}</b><span>{formatEther(p.amount)} tBNB</span><small>{p.state===0?'PENDING DECISION':p.state===1?'TEMPORARILY LOCKED':'ALLOCATED'}</small>{p.state===1&&<Countdown until={p.temporaryUnlockAt}/>}</div>{p.state===0&&<div className="actions">{presets.filter(x=>!x.archived&&!x.deleted).map(pr=><button key={pr.id} onClick={()=>allocate(p,pr.onchainPresetId)}>Use {pr.name}</button>)}<button onClick={()=>lock(p)}>Temporary 1h lock</button></div>}{p.state===1&&<div className="actions"><button disabled={Date.now()<Number(p.temporaryUnlockAt)*1000} onClick={()=>expire(p)}>Reopen decision</button><button disabled={Date.now()<Number(p.temporaryUnlockAt)*1000+15*60*1000} onClick={()=>relock(p)}>Re-lock after 15m</button></div>}{p.state===2&&<AllocationList ids={p.allocations} onUnlock={unlock} onWithdraw={withdraw} client={client} vault={vault}/>}</div>)}</section>}
<section className="card"><span className="label">IN-APP NOTIFICATIONS</span>{notifications.length?notifications.slice(0,10).map(n=><div className="notice" key={n.id}>{n.message}<small>{new Date(n.createdAt).toLocaleString()}</small></div>):<p className="muted">No notifications yet.</p>}</section>
<footer><span>{status}</span><span>V1 · BSC Testnet only · No custody · No AI signing</span></footer></main>}

function AllocationList({ids,onUnlock,onWithdraw,client,vault}:{ids:bigint[];onUnlock:(id:bigint)=>void;onWithdraw:(id:bigint,a:bigint)=>void;client:any;vault:Address|null}){const[data,setData]=useState<any[]>([]);useEffect(()=>{if(!client||!vault)return;Promise.all(ids.map(id=>client.readContract({address:vault,abi:vaultAbi,functionName:'allocations',args:[id]}))).then(setData)},[ids,client,vault]);return <div className="allocations">{data.map((a:any,i)=><div className="allocation" key={ids[i].toString()}><span>Allocation #{ids[i].toString()} · {formatEther(a[3])} tBNB</span>{a[6]?<small>Spent</small>:a[5]?<button onClick={()=>onWithdraw(ids[i],a[3])}>Authorize spending</button>:Date.now()<Number(a[4])*1000?<Countdown until={a[4]}/>:<button onClick={()=>onUnlock(ids[i])}>Authorize unlock</button>}</div>)}</div>}
